import type { FastifyInstance } from 'fastify'
import { defaultCommissionConfig as config } from '@/config/commissionConfig'
import { calculateReferralCommission } from '@/domain/commissionEngine'
import { parseISO } from '@/domain/dateUtils'
import { HttpError, notFound } from '../errors'
import type { Store } from '../store'

interface CreateReferralBody {
  referredDistributorId: string
  /** The applicable distributor fee, in cents. */
  fee: number
  date?: string
}

const createReferralSchema = {
  body: {
    type: 'object',
    required: ['referredDistributorId', 'fee'],
    additionalProperties: false,
    properties: {
      referredDistributorId: { type: 'string', minLength: 1 },
      fee: { type: 'integer', minimum: 1, maximum: 100_000_000_00 },
      date: { type: 'string' },
    },
  },
} as const

const payReferralSchema = {
  body: {
    type: 'object',
    required: ['paymentStatus'],
    additionalProperties: false,
    properties: { paymentStatus: { type: 'string', enum: ['PAID'] } },
  },
} as const

export function commissionRoutes(app: FastifyInstance, store: Store) {
  app.get('/api/commissions/ledger', async () => store.ledger())

  app.get('/api/referrals', async () => store.referrals.list())

  /**
   * Record a fee generated by a referred distributor. The referrer is whoever referred them (never sent by the
   * client, so the two can't disagree) and the commission is calculated here from the configured percentage.
   */
  app.post<{ Body: CreateReferralBody }>(
    '/api/referrals',
    { schema: createReferralSchema },
    async (request, reply) => {
      const { referredDistributorId, fee } = request.body
      const now = new Date()

      const referred = await store.distributors.get(referredDistributorId)
      if (!referred) throw notFound('Distributor', referredDistributorId)
      if (!referred.referredBy) {
        throw new HttpError(
          422,
          `${referred.id} was not referred by anyone, so there is no referral commission`,
        )
      }

      const date = request.body.date === undefined ? now : parseISO(request.body.date)
      if (!date) throw new HttpError(400, 'date must be a valid ISO-8601 timestamp')
      if (date.getTime() > now.getTime())
        throw new HttpError(422, 'A referral cannot be dated in the future')
      if (date.getTime() < Date.parse(referred.joinedAt)) {
        throw new HttpError(
          422,
          `A referral cannot predate the referred distributor joining (${referred.id})`,
        )
      }

      const created = await store.referrals.create({
        referringDistributorId: referred.referredBy,
        referredDistributorId: referred.id,
        date: date.toISOString(),
        fee,
        percentage: config.referralPercentage,
        commission: calculateReferralCommission(fee, config.referralPercentage),
        paymentStatus: 'PENDING',
      })
      return reply.status(201).header('location', `/api/referrals/${created.id}`).send(created)
    },
  )

  /** Mark a referral commission as paid. Idempotent: paying an already-paid referral is a no-op. */
  app.patch<{ Params: { id: string }; Body: { paymentStatus: 'PAID' } }>(
    '/api/referrals/:id',
    { schema: payReferralSchema },
    async (request) => {
      const referral = await store.referrals.markPaid(request.params.id)
      if (!referral) throw notFound('Referral', request.params.id)
      return referral
    },
  )
}
