import type { ISODateString, Money } from './common'

export type LedgerEntryType =
  'ONBOARDING' | 'RETAILER_SALE' | 'DISTRIBUTOR_REFERRAL' | 'DOWNLINE_SALE'

export type LedgerStatus = 'EARNED' | 'PENDING'

/** `"COMPANY"` or a distributor id such as `"DIST-001"`. */
export type LedgerEntity = string

export interface LedgerEntry {
  id: string
  date: ISODateString
  entity: LedgerEntity
  /** Distributor whose activity produced this entry. Used for state scoping and hierarchy tracing. */
  distributorId: string
  type: LedgerEntryType
  /** Retailer id, invoice id or distributor id that produced this entry. */
  reference: string
  amount: Money
  status: LedgerStatus
}

export interface Referral {
  id: string
  referringDistributorId: string
  referredDistributorId: string
  date: ISODateString
  /** The applicable distributor fee generated by the referred distributor. */
  fee: Money
  percentage: number
  commission: Money
  paymentStatus: 'PENDING' | 'PAID'
}
