import { Plus } from 'lucide-react'
import { useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { DashboardCard } from '@/components/common/DashboardCard'
import { DataTable, type Column } from '@/components/common/DataTable'
import { DateRangeFilter, FilterBar, SelectFilter } from '@/components/common/Filters'
import { FormMessage } from '@/components/common/FormField'
import { PageHeader } from '@/components/common/PageHeader'
import { StatusBadge } from '@/components/common/StatusBadge'
import { RecordReferralForm } from '@/components/features/RecordReferralForm'
import { Button } from '@/components/ui/Button'
import { defaultCommissionConfig } from '@/config/commissionConfig'
import { isWithinDayRange, parseISO } from '@/domain/dateUtils'
import { sumMoney } from '@/domain/money'
import { useCommissions } from '@/hooks/useCommissions'
import { usePayReferral } from '@/hooks/useEntryMutations'
import { useMarketplaceData } from '@/hooks/useMarketplaceData'
import { useUrlFilters } from '@/hooks/useUrlFilters'
import { ApiError } from '@/services/apiClient'
import type { Referral } from '@/types'
import { formatCurrency } from '@/utils/currencyFormatter'
import { formatDate, humanize } from '@/utils/dateFormatter'

export default function Referrals() {
  const { referrals, nameById, isLoading, error, refetch } = useCommissions()
  const { all } = useMarketplaceData()
  const pay = usePayReferral()
  const [formOpen, setFormOpen] = useState(false)
  const [payError, setPayError] = useState<string | null>(null)
  const [filters, update] = useUrlFilters(['status', 'from', 'to'])

  const rows = useMemo(
    () =>
      referrals.filter((referral) => {
        if (filters.status && referral.paymentStatus !== filters.status) return false
        const date = parseISO(referral.date)
        return date
          ? isWithinDayRange(
              date,
              filters.from,
              filters.to,
              defaultCommissionConfig.businessTimeZone,
            )
          : false
      }),
    [referrals, filters],
  )

  const totals = useMemo(() => {
    const paid = sumMoney(rows.filter((r) => r.paymentStatus === 'PAID').map((r) => r.commission))
    const pending = sumMoney(
      rows.filter((r) => r.paymentStatus === 'PENDING').map((r) => r.commission),
    )
    return { paid, pending, all: paid + pending }
  }, [rows])

  const markPaid = (id: string) => {
    setPayError(null)
    pay.mutate(id, {
      onError: (e) => setPayError(e instanceof ApiError ? e.message : 'Something went wrong.'),
    })
  }

  const distributorCell = (id: string) => (
    <Link to={`/distributors/${id}`} className="text-brand hover:underline">
      {nameById.get(id) ?? id} <span className="text-ink-2">({id})</span>
    </Link>
  )

  const columns: Column<Referral>[] = [
    { key: 'date', header: 'Date', cell: (r) => formatDate(r.date), sortValue: (r) => r.date },
    {
      key: 'referrer',
      header: 'Referring distributor',
      cell: (r) => distributorCell(r.referringDistributorId),
      sortValue: (r) => r.referringDistributorId,
    },
    {
      key: 'referred',
      header: 'Referred distributor',
      cell: (r) => distributorCell(r.referredDistributorId),
      sortValue: (r) => r.referredDistributorId,
    },
    {
      key: 'fee',
      header: 'Distributor fee',
      align: 'right',
      cell: (r) => formatCurrency(r.fee),
      sortValue: (r) => r.fee,
      footer: (rowsAll) => formatCurrency(sumMoney(rowsAll.map((r) => r.fee))),
    },
    {
      key: 'pct',
      header: '%',
      align: 'right',
      cell: (r) => `${r.percentage}%`,
      sortValue: (r) => r.percentage,
    },
    {
      key: 'commission',
      header: 'Commission',
      align: 'right',
      cell: (r) => formatCurrency(r.commission),
      sortValue: (r) => r.commission,
      footer: (rowsAll) => formatCurrency(sumMoney(rowsAll.map((r) => r.commission))),
    },
    {
      key: 'status',
      header: 'Payment',
      cell: (r) => <StatusBadge status={r.paymentStatus} />,
      sortValue: (r) => r.paymentStatus,
    },
    {
      key: 'action',
      header: <span className="sr-only">Action</span>,
      align: 'right',
      cell: (r) =>
        r.paymentStatus === 'PENDING' ? (
          <Button
            variant="secondary"
            disabled={pay.isPending}
            onClick={() => markPaid(r.id)}
            aria-label={`Mark ${r.id} as paid`}
          >
            Mark paid
          </Button>
        ) : null,
    },
  ]

  const nothingYet =
    !isLoading &&
    !error &&
    referrals.length === 0 &&
    !filters.status &&
    !filters.from &&
    !filters.to

  return (
    <>
      <PageHeader
        title="Referrals"
        description="A referring distributor earns a share of the fee generated by the distributor they referred."
        actions={
          <Button variant="primary" disabled={formOpen} onClick={() => setFormOpen(true)}>
            <Plus className="size-4" />
            Record referral fee
          </Button>
        }
      />

      {formOpen && (
        <RecordReferralForm
          distributors={all?.distributors ?? []}
          onClose={() => setFormOpen(false)}
        />
      )}
      {payError && (
        <div className="mb-4">
          <FormMessage tone="error">{payError}</FormMessage>
        </div>
      )}

      <div className="mb-4 grid gap-4 sm:grid-cols-3">
        <DashboardCard
          label="Total referral commission"
          value={formatCurrency(totals.all)}
          loading={isLoading}
        />
        <DashboardCard label="Paid" value={formatCurrency(totals.paid)} loading={isLoading} />
        <DashboardCard label="Pending" value={formatCurrency(totals.pending)} loading={isLoading} />
      </div>

      <DataTable
        caption="Distributor referrals"
        columns={columns}
        rows={rows}
        rowKey={(r) => r.id}
        isLoading={isLoading}
        error={error}
        onRetry={refetch}
        initialSort={{ key: 'date', direction: 'desc' }}
        emptyTitle={nothingYet ? 'No referrals yet' : 'No referrals found'}
        emptyDescription={
          nothingYet
            ? 'When adding a distributor, choose who referred them. Then use "Record referral fee" to enter the fees they generate.'
            : 'Try a different status or date range.'
        }
        toolbar={
          <FilterBar>
            <SelectFilter
              label="Payment status"
              value={filters.status as 'PAID' | 'PENDING' | ''}
              onChange={(status) => update({ status })}
              options={[
                { value: '', label: 'All' },
                { value: 'PAID', label: humanize('PAID') },
                { value: 'PENDING', label: humanize('PENDING') },
              ]}
            />
            <DateRangeFilter from={filters.from} to={filters.to} onChange={update} />
          </FilterBar>
        }
      />
    </>
  )
}
