import { useMemo } from 'react'
import { Link } from 'react-router-dom'
import { DashboardCard } from '@/components/common/DashboardCard'
import { DataTable, type Column } from '@/components/common/DataTable'
import { DateRangeFilter, FilterBar, SelectFilter } from '@/components/common/Filters'
import { PageHeader } from '@/components/common/PageHeader'
import { StatusBadge } from '@/components/common/StatusBadge'
import { defaultCommissionConfig } from '@/config/commissionConfig'
import { isWithinDayRange, parseISO } from '@/domain/dateUtils'
import { sumMoney } from '@/domain/money'
import { useCommissions } from '@/hooks/useCommissions'
import { useUrlFilters } from '@/hooks/useUrlFilters'
import type { Referral } from '@/types'
import { formatCurrency } from '@/utils/currencyFormatter'
import { formatDate, humanize } from '@/utils/dateFormatter'

export default function Referrals() {
  const { referrals, nameById, isLoading, error, refetch } = useCommissions()
  const [filters, update] = useUrlFilters(['status', 'from', 'to'])

  const rows = useMemo(
    () =>
      referrals.filter((referral) => {
        if (filters.status && referral.paymentStatus !== filters.status) return false
        const date = parseISO(referral.date)
        return date
          ? isWithinDayRange(
              date,
              filters.from,
              filters.to,
              defaultCommissionConfig.businessTimeZone,
            )
          : false
      }),
    [referrals, filters],
  )

  const totals = useMemo(() => {
    const paid = sumMoney(rows.filter((r) => r.paymentStatus === 'PAID').map((r) => r.commission))
    const pending = sumMoney(
      rows.filter((r) => r.paymentStatus === 'PENDING').map((r) => r.commission),
    )
    return { paid, pending, all: paid + pending }
  }, [rows])

  const distributorCell = (id: string) => (
    <Link to={`/distributors/${id}`} className="text-brand hover:underline">
      {nameById.get(id) ?? id} <span className="text-ink-2">({id})</span>
    </Link>
  )

  const columns: Column<Referral>[] = [
    { key: 'date', header: 'Date', cell: (r) => formatDate(r.date), sortValue: (r) => r.date },
    {
      key: 'referrer',
      header: 'Referring distributor',
      cell: (r) => distributorCell(r.referringDistributorId),
      sortValue: (r) => r.referringDistributorId,
    },
    {
      key: 'referred',
      header: 'Referred distributor',
      cell: (r) => distributorCell(r.referredDistributorId),
      sortValue: (r) => r.referredDistributorId,
    },
    {
      key: 'fee',
      header: 'Distributor fee',
      align: 'right',
      cell: (r) => formatCurrency(r.fee),
      sortValue: (r) => r.fee,
      footer: (all) => formatCurrency(sumMoney(all.map((r) => r.fee))),
    },
    {
      key: 'pct',
      header: '%',
      align: 'right',
      cell: (r) => `${r.percentage}%`,
      sortValue: (r) => r.percentage,
    },
    {
      key: 'commission',
      header: 'Commission',
      align: 'right',
      cell: (r) => formatCurrency(r.commission),
      sortValue: (r) => r.commission,
      footer: (all) => formatCurrency(sumMoney(all.map((r) => r.commission))),
    },
    {
      key: 'status',
      header: 'Payment',
      cell: (r) => <StatusBadge status={r.paymentStatus} />,
      sortValue: (r) => r.paymentStatus,
    },
  ]

  return (
    <>
      <PageHeader
        title="Referrals"
        description="A referring distributor earns a share of the fee generated by the distributor they referred."
      />

      <div className="mb-4 grid gap-4 sm:grid-cols-3">
        <DashboardCard
          label="Total referral commission"
          value={formatCurrency(totals.all)}
          loading={isLoading}
        />
        <DashboardCard label="Paid" value={formatCurrency(totals.paid)} loading={isLoading} />
        <DashboardCard label="Pending" value={formatCurrency(totals.pending)} loading={isLoading} />
      </div>

      <DataTable
        caption="Distributor referrals"
        columns={columns}
        rows={rows}
        rowKey={(r) => r.id}
        isLoading={isLoading}
        error={error}
        onRetry={refetch}
        initialSort={{ key: 'date', direction: 'desc' }}
        emptyTitle="No referrals found"
        emptyDescription="Referral commissions appear here when a referred distributor generates a fee."
        toolbar={
          <FilterBar>
            <SelectFilter
              label="Payment status"
              value={filters.status as 'PAID' | 'PENDING' | ''}
              onChange={(status) => update({ status })}
              options={[
                { value: '', label: 'All' },
                { value: 'PAID', label: humanize('PAID') },
                { value: 'PENDING', label: humanize('PENDING') },
              ]}
            />
            <DateRangeFilter from={filters.from} to={filters.to} onChange={update} />
          </FilterBar>
        }
      />
    </>
  )
}
