-- Initial schema. Money is BIGINT cents; instants are TIMESTAMPTZ (stored in UTC).
-- IDs are generated by the database from sequences, so records can be created one at a time
-- (and by several requests at once) without ever colliding.

CREATE SEQUENCE distributor_seq START 1;
CREATE SEQUENCE retailer_seq    START 1001;
CREATE SEQUENCE sale_invoice_seq START 1001;
CREATE SEQUENCE referral_seq    START 1;

CREATE TABLE distributors (
  id            TEXT PRIMARY KEY DEFAULT ('DIST-' || lpad(nextval('distributor_seq')::text, 3, '0')),
  name          TEXT NOT NULL CHECK (length(btrim(name)) > 0),
  state         TEXT NOT NULL,
  city          TEXT NOT NULL,
  parent_id     TEXT REFERENCES distributors(id),
  position      TEXT CHECK (position IN ('LEFT', 'RIGHT')),
  referred_by   TEXT REFERENCES distributors(id),
  daily_target  INTEGER NOT NULL CHECK (daily_target >= 0),
  joined_at     TIMESTAMPTZ NOT NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  -- a placed distributor needs a side; a top-level one must not have one
  CHECK ((parent_id IS NULL) = (position IS NULL)),
  CHECK (parent_id IS DISTINCT FROM id),
  CHECK (referred_by IS DISTINCT FROM id),
  -- a slot holds one child: the binary-tree rule, enforced by the database itself
  UNIQUE (parent_id, position)
);
CREATE INDEX idx_distributors_state ON distributors(state);

CREATE TABLE retailers (
  id              TEXT PRIMARY KEY DEFAULT ('RET-' || nextval('retailer_seq')::text),
  name            TEXT NOT NULL CHECK (length(btrim(name)) > 0),
  distributor_id  TEXT NOT NULL REFERENCES distributors(id),
  state           TEXT NOT NULL,
  city            TEXT NOT NULL,
  phone           TEXT,
  onboarded_at    TIMESTAMPTZ NOT NULL,
  status          TEXT NOT NULL CHECK (status IN ('ACTIVE', 'DEACTIVATED', 'CANCELLED')),
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_retailers_distributor ON retailers(distributor_id);

CREATE TABLE sales (
  invoice_no              BIGINT NOT NULL UNIQUE DEFAULT nextval('sale_invoice_seq'),
  id                      TEXT PRIMARY KEY GENERATED ALWAYS AS ('INV-' || invoice_no) STORED,
  retailer_id             TEXT NOT NULL REFERENCES retailers(id),
  distributor_id          TEXT NOT NULL REFERENCES distributors(id),
  date                    TIMESTAMPTZ NOT NULL,
  product                 TEXT NOT NULL CHECK (length(btrim(product)) > 0),
  quantity                INTEGER NOT NULL CHECK (quantity > 0),
  amount                  BIGINT NOT NULL CHECK (amount > 0),
  retailer_commission     BIGINT NOT NULL CHECK (retailer_commission >= 0),
  distributor_commission  BIGINT NOT NULL CHECK (distributor_commission >= 0),
  company_commission      BIGINT NOT NULL CHECK (company_commission >= 0),
  remainder               BIGINT NOT NULL CHECK (remainder >= 0),
  created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
  -- nothing may be lost: the four shares always add back up to the sale, to the cent
  CHECK (retailer_commission + distributor_commission + company_commission + remainder = amount)
);
CREATE INDEX idx_sales_retailer ON sales(retailer_id);
CREATE INDEX idx_sales_distributor ON sales(distributor_id);
CREATE INDEX idx_sales_date ON sales(date);

CREATE TABLE referrals (
  id                        TEXT PRIMARY KEY DEFAULT ('REF-' || lpad(nextval('referral_seq')::text, 4, '0')),
  referring_distributor_id  TEXT NOT NULL REFERENCES distributors(id),
  referred_distributor_id   TEXT NOT NULL REFERENCES distributors(id),
  date                      TIMESTAMPTZ NOT NULL,
  fee                       BIGINT NOT NULL CHECK (fee >= 0),
  percentage                NUMERIC(5, 2) NOT NULL CHECK (percentage >= 0 AND percentage <= 100),
  commission                BIGINT NOT NULL CHECK (commission >= 0),
  payment_status            TEXT NOT NULL CHECK (payment_status IN ('PENDING', 'PAID')),
  created_at                TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (referring_distributor_id <> referred_distributor_id)
);
CREATE INDEX idx_referrals_referring ON referrals(referring_distributor_id);
